apiVersion: apps/v1
kind: Deployment
metadata:
  name: site-deployment
  namespace: kubernetes-101-namespace
  labels:
    app: site
spec:
  replicas: 2
  selector:
    matchLabels:
      app: site
  template:
    metadata:
      labels:
        app: site
    spec:
      containers:
      - name: site
        image: wordpress:php8.1-apache
        ports:
        - containerPort: 80
        readinessProbe:
          initialDelaySeconds: 2
          periodSeconds: 5
          httpGet:
            path: /
            port: 80
        livenessProbe:
          initialDelaySeconds: 2
          periodSeconds: 5
          httpGet:
            path: /
            port: 80
        env:
        - name: WORDPRESS_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: database-config-map
              key: database-host
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: database-username
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: database-password
        - name: WORDPRESS_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: database-config-map
              key: database-name
