apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: kubernetes-101-namespace
type: Opaque
data:
  # database-username: "username" encoded in Base64 - 'echo -n "username" | base64'
  database-username: dXNlcm5hbWU=
  # database-password: "password" encoded in Base64 - 'echo -n "password" | base64'
  database-password: cGFzc3dvcmQ=
