kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: database-persistent-volume-claim
  namespace: kubernetes-101-namespace
spec:
  storageClassName: my-local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
