apiVersion: v1
kind: Secret
metadata:
  name: database-secret
type: Opaque
data:
  # database-username: "mysql" encoded in Base64
  database-username: bXlzcWw=
  # database-password: "mysql" encoded in Base64
  database-password: bXlzcWw=
