apiVersion: v1
kind: Pod
metadata:
  name: database-admin-pod
spec:
  containers:
  - name: database-admin
    image: phpmyadmin:5.2.0-apache
    ports:
    - containerPort: 80
    readinessProbe:
      initialDelaySeconds: 2
      periodSeconds: 5
      httpGet:
        path: /
        port: 80
    env:
    - name: PMA_HOST
      value: "database-service"
    - name: PMA_USER
      valueFrom:
        secretKeyRef:
          name: database-secret
          key: database-username
    - name: PMA_PASSWORD
      valueFrom:
        secretKeyRef:
          name: database-secret
          key: database-password
