version: '2.0'

services:
  site:
    image: wordpress:php8.1-apache
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_USER: username
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress_db
  database:
    image: mysql:8.0.29
    environment:
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./database:/var/lib/mysql
  database_admin:
    image: phpmyadmin:5.2.0-apache
    ports:
      - "8081:80"
    environment:
      PMA_HOST: database
      PMA_USER: username
      PMA_PASSWORD: password
